### ISSUE TITLE
insmod: ERROR: could not insert module

### ISSUE THREAD

**Issue by draakje111** [gpopesc/wireguard-module-synology#1]
Hi I'm trying to install the wireguard module but I get an error that it is in the wrong format.

insmod: ERROR: could not insert module /lib/modules/wireguard.ko: Invalid module format

I run a DS415+ runs on x64 is that module compatible with every synology or only arm based?

Thanks for your post I'm trying to get wireguard installed with portainer and read over your posts in wg-easy

**Comment by gpopesc** [comment]
replace mine (wireguard.ko) with this one attached and then run the script.
It depends of  CPU.
[avoton.zip](https://github.com/gpopesc/wireguard-module-synology/files/10345083/avoton.zip)

Here they are all wireguard builds for synology. It needs to change the extension in zip and then extract the files. I extract the file for you.

**Comment by gpopesc** [comment]
closed, as it is solved

**Comment by gpopesc** [comment]
closed, as it is solved.
