### ISSUE TITLE
Synology restarts

### ISSUE THREAD

**Issue by rtmlp** [gpopesc/wireguard-module-synology#2]
Hi,

Thanks a lot for creating the bash script. I am able to run the script and use linuxserver wireguard container. 

Do I need to create a startup command to run this script everytime synology restarts/updates ?

Thanks

**Comment by gpopesc** [comment]
hi,

It is not necessary to run the script every restart or minor updates (ex: 7.1.xxx).
Probably it will be requested only for major updates. ex: 7.1 or 7.2

**Comment by rtmlp** [comment]
Thank you for the answer
