### ISSUE TITLE
Recommended Removal Method

### ISSUE THREAD

**Issue by edlucky1** [gpopesc/wireguard-module-synology#3]
Is there a recommended method for removal?

I installed this on my DS923+ (7.2) and the NAS immediately crashes when I spin up the linuxserver image. I would like to remove these files so that other users do not accidentally crash the NAS doing the same.

Edit: The install script succeeded with no errors.

**Comment by gpopesc** [comment]
Normally you should get an error at installation and no further steps would be necessary.
If by any chance, you managed to install the module, then you can run following commands to uninstall it:
`sudo rmmod /lib/modules/wireguard.ko`
`sudo rm -i /lib/modules/wireguard.ko`
`sudo rm -i /usr/local/etc/rc.d/wireguard.sh`
 
if you still want to install it, for you version 923+, try replace my wireguard.ko with one from archive bellow (depending of DSM version 7.1 or 7.2)
[wireguard_R1000_7.1.zip](https://github.com/gpopesc/wireguard-module-synology/files/14625596/wireguard_R1000_7.1.zip)
[wireguard_R1000_7.2.zip](https://github.com/gpopesc/wireguard-module-synology/files/14625597/wireguard_R1000_7.2.zip)

**Comment by edlucky1** [comment]
I did not get an errors, it stated everything was successful and the file showed in the correct system folder afterwards. Any testing I can do to debug the lack of errors? I don't mind trying something before switching to the file you provided.

**Comment by gpopesc** [comment]
errors (if there is any) are in the new created file: log.txt in the folder where execute the batch file.
when I create this tool, I made it for personal use (usually you need to execute again after big DSM upgrades). If I will have time I will make a menu at batch start to choose the DSM version and processor.
So, if you want to use, simple replace my wireguard.ko with one of the versions provided above and run again the script.
At the end, check the the existence of log.txt in the same folder. (delete log.txt if there is one in the folder before executing batch - I will insert that in the next version of script)

**Comment by edlucky1** [comment]
Yes I understand the error log. My assumption is that I should have received an error if I installed the wrong file for my NAS/DSM combo. I did not receive an error, nor was an error log created. If you need help investigating why that is I can provide testing. Otherwise, I will just install the new file and forget about it, but likely other users will run into same issue unless corrected.

**Comment by edlucky1** [comment]
Removal instructions worked well, new file solved my issue. Closing this issue. If you want to add to your script errors feel free to reopen and provide next steps.

**Comment by gpopesc** [comment]
I made a new version,  for all major models. your are free to use as you wish!
